### ISSUE TITLE
Integrate mocha's test suite to test functions

### ISSUE THREAD

**Issue by iagorm** [iagorm/brazil-correios-tracking#1]
## Description

The integration with Mocha should be able to create suite tests to avoid possible unexpected errors. 

## Acceptance Criteria

- [ ]  The application can be tested by using mocha
- [ ]  There must be at least one test done that passes

**Comment by paulolorenzobasilio** [comment]
I would love to work on this.

**Comment by iagorm** [comment]
@paulolorenzobasilio you are allowed to work on this issue.
