### ISSUE TITLE
Add a better structure to the application

### ISSUE THREAD

**Issue by iagorm** [iagorm/brazil-correios-tracking#2]
## Description

The application must receive a split structure into the following layers:

```
- src
   |- index.js
   |- routes
   |- controllers
   |- middlewares
   |- lib
       |- formatters.js
```

## Acceptance Criteria

- [ ] The structure follows the necessity

**Comment by DiegoBousfield** [comment]
All you want is a new folder structure? Could I do that?

**Comment by jhidalgoesp** [comment]
@iagorm , Hello I created a MR addressing this issue (#4).

**Comment by iagorm** [comment]
> @iagorm , Hello I created a MR addressing this issue (#4).

@jhidalgoesp I will review this ASAP.
