### ISSUE TITLE
Show dynamically a list of packages

### ISSUE THREAD

**Issue by iagorm** [iagorm/brazil-correios-tracking#3]
## Description

Create a new route to allow the API to send an array of packages to avoid multiple requests from the client-side, also they can be sorted by progress and date.

## Acceptance Criteria

- [ ] The request receives an array of the package id
- [ ] The response can be sorted by progress and date

**Comment by DiegoBousfield** [comment]
May I take that issue?

**Comment by iagorm** [comment]
> May I take that issue?

@DiegoBousfield  Sure!
